name: Build all images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "build-${{ matrix.img }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        img:
         - full
         - customizable
         - nodejs
         - jruby94
         - jruby93
         - ruby32
         - ruby31
         - ruby30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Purge containers
        run: 'docker kill $(docker ps -q) || exit 0'
      - name: Enable docker multiarch
        run: 'docker run --privileged --rm tonistiigi/binfmt --install all'
      - name: "Run make build_${{ matrix.img }}"
        run: "make build_${{ matrix.img }}"
      - name: Log in to the Container registry
        if: ${{ github.event.pull_request.merged || github.actor == 'CamJN' }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to github container registry
        if: ${{ success() }}
        run: "make release_${{ matrix.img }}"
